export const QUESTIONS = [
  "What are your hobbies and interests?",
  "Are you clean or messy?",
  "Are you punctual or fashionably late?",
  "List 3 physical items you like.",
  "How do you like your coffee?",
  "How do you like to spend your free time?",
  "What are your favorite books/authors?",
  "What are your favorite movies/genres?",
  "Do you have any favorite TV shows or series?",
  "What kind of music do you enjoy listening to?",
  "What places can you realistically and plan to visit within the next year?",
  "What's your favorite way to relax or unwind?",
  "What are some of your long-term goals or dreams?",
  "Describe your ideal friendship.",
  "What are your pet peeves or things you dislike?",
  "What's your favorite season and why?",
  "Do you have any favorite quotes or mottos that inspire you?",
  "What's your idea of a perfect day?",
  "What's something you've always wanted to learn or try?",
  "What's your biggest fear or phobia?",
  "What do you admire most about yourself?",
  "What's something you wish you were better at?",
  "What's your favorite childhood memory?",
  "Is there anything you wish I knew about you or understood better?",
  "What topics are off limits between us?",
  "What qualities about me do you like?",
  "What qualities about me do you dislike?",
  "What do you think I should improve on?",
  "What is your favorite color?",
  "What political party do your ideologies align with?",
  "Are you more creative or analytical?",
  "Do you prefer routine or spontaneity?",
  "What is your favorite animal and why?",
  "Are you passionate enough about animals to join PETA?",
  "Knowing that orcas have sophisticated social structures, communication, problem-solving, empathy, cultural traditions, and self-awareness, do you agree it is cruel and inhumane for orcas to be held in captivity in the SeaWorld franchise?",
  "Would you be interested in helping me prepare a bill in Congress that would make it illegal to own orcas for any purpose and declare orcas as a protected class of non-human persons with rights and protections?",
  "What law(s) do you absolutely disagree with?",
  "When you tell me something negative, would you prefer me to not ask questions and just listen, or become involved in a solution?",
  "Do you think marijuana should be legal?",
  "If you could live in any era of history, which one would you choose and why?",
  "What's the most unusual or adventurous thing you've ever done?",
  "What\u2019s your favorite food type or meal?",
  "Who is your favorite celebrity of all time and why? Could be authors, writers, politicians, or artists.",
  "What's a hobby or interest you've always wanted to pursue but never got around to?",
  "What\u2019s a hobby or interest you would specifically like to do with me?",
  "Do you like Virtual Reality?",
  "I have the ability for us to watch any movie we want at the same time remotely. This is a great way to share quality time when we\u2019re not in person. Are you interested?",
  "What's the most memorable dream you've ever had?",
  "How do you feel about religion?",
  "Do you believe in a God?",
  "Do you believe in Jesus?",
  "What is your biggest talent?",
  "What's the most spontaneous thing you've ever done?",
  "Have you ever cheated on one or more people? If so, how many?",
  "Would you ever cheat on someone?",
  "Is it ever morally justifiable to break the law? If so, in what scenario?",
  "Should euthanasia be legalized for terminally ill patients who are suffering?",
  "Is it ethical to use animals for scientific experiments or testing?",
  "Are you pro-choice, or do you think abortion should be illegal?",
  "Should parents have the right to genetically modify their children before birth?",
  "Is it morally acceptable to prioritize the lives of humans over animals in all circumstances?",
  "Is it ethical to consume products that are known to be produced through child labor?",
  "Should individuals have the right to end their own life through certified euthanasia programs if they are suffering from severe mental illness?",
  "Is it ever justifiable to lie to protect someone's feelings or prevent harm?",
  "Should the death penalty be abolished?",
  "Is it ethical to use artificial intelligence in decision-making processes that affect human lives?",
  "Is it ethical to redistribute wealth to address socioeconomic inequality, or should successful wealthy people not be penalized for their success?",
  "Is it ethical to use technology to enhance human capabilities, such as cognitive or physical abilities?",
  "Is it morally permissible to clone humans?",
  "You find a wallet containing a large sum of money and the owner's identification. Do you keep the money, return it intact, or report it to the authorities?",
  "You witness a friend cheating on a significant other. Do you confront your friend, keep their secret, or inform the partner?",
  "You're in a lifeboat adrift at sea with limited supplies and too many people. Do you prioritize saving yourself, sacrifice others for the greater good, or find an alternative solution?",
  "You're a doctor with only enough medication to save one patient out of two who need it urgently. How do you decide who receives treatment?",
  "You're offered a job with a significantly higher salary but involves morally questionable practices. Do you accept the job for financial gain or maintain your integrity?",
  "You discover that a colleague is being unfairly treated or discriminated against at work. Do you speak up on their behalf, risking your own position, or stay silent to avoid conflict?",
  "You witness an act of injustice but fear retaliation if you intervene. Do you report the incident, even if it puts you at risk, or remain silent to protect yourself?",
  "You're aware of a company's unethical practices that harm the environment. Do you expose the wrongdoing publicly, risking legal consequences, or remain silent to avoid repercussions?",
  "You're asked to testify in court about a crime you witnessed, but doing so could endanger your safety or the safety of your loved ones. Do you testify truthfully, withhold information, or lie to protect yourself?",
  "You're offered the opportunity to advance in your career by taking credit for someone else's work. Do you accept the recognition, confront the person who deserves credit, or refuse to participate in the deception?",
  "You witness a friend driving under the influence of alcohol. Do you intervene to prevent them from driving, offer to call a cab or drive them home yourself, or let them make their own choices?",
  "You're in a position of power and influence, and you have the opportunity to enact positive change but at the expense of personal relationships or career advancement. Do you prioritize making a difference or maintaining your status quo?",
  "You accidentally damage someone else's property, but nobody saw you do it. Do you take responsibility and offer to repair or replace the item, or do you remain silent and avoid the consequences?",
  "You're asked to keep a secret that could harm someone if it were to be revealed. Do you honor your promise of confidentiality, or do you disclose the information to prevent harm?",
  "You're faced with a decision that goes against your personal beliefs or values but is expected by society or your community. Do you conform to social expectations, or do you stay true to yourself, even if it means facing criticism or ostracism?",
  "Have you been diagnosed with any health conditions? If yes, please explain.",
  "Have you been diagnosed with any mental health conditions? If yes, please explain. If yes, please also include any medications you\u2019re prescribed to take on a regular basis.",
  "Would you consider yourself a good, safe, and defensive driver?",
  "How many traffic violations have you received since driving age?",
  "How many accidents, by fault or no fault of your own, have you been in?",
  "Is there a serious topic that you think you and I need to discuss?",
  "If we have conflict in our friendship, would you be willing to resolve it by participating in a one-hour telehealth remote therapy session with me?",
  "Do you want to have children? If so, how many, what genders, and what timeframe?",
  "Is there one or more things you would like to know about me and have not asked? Here\u2019s your chance. You can ask anything without fear of consequence.",
  "Is there anything that I have not asked, or do not know about you, that you would like to share?"
];
